
REPORT ZEXAMPLE_ABAP2EXEL.


DATA: VL_LINEASTOTALES TYPE I,
      VL_MONTOSTOTALES TYPE RFWRT,
      TL_LIBROS TYPE STANDARD TABLE OF ZSTSD_LIBROS_XLSX,
      TL_DATA TYPE STANDARD TABLE OF ZSTSD_DATA_XLSX,
      TL_MERGECELLS TYPE STANDARD TABLE OF ZSTSD_MERGECELLS_XLSX,
      TL_TOTALES TYPE STANDARD TABLE OF ZSTSD_TOTALES_XLSX.

 CLEAR: TL_LIBROS[], TL_DATA[].
 REFRESH: TL_LIBROS[], TL_DATA[].

********************************* Libro 1 ******************************
 APPEND INITIAL LINE TO TL_LIBROS ASSIGNING FIELD-SYMBOL(<FS_LIBROS>).
  <FS_LIBROS>-INDEXLIBRO = 1.
  <FS_LIBROS>-LIBRO = 'Libro 1'.

  APPEND INITIAL LINE TO TL_DATA ASSIGNING FIELD-SYMBOL(<FS_DATA>).
  <FS_DATA>-INDEXLIBRO = 1.
  <FS_DATA>-COLUMNA = 'A'.
  <FS_DATA>-CABECERA = ABAP_TRUE.
  <FS_DATA>-DATA = 'Celda 1'.

  APPEND INITIAL LINE TO TL_DATA ASSIGNING <FS_DATA>.
  <FS_DATA>-INDEXLIBRO = 1.
  <FS_DATA>-COLUMNA = 'B'.
  <FS_DATA>-CABECERA = ABAP_TRUE.
  <FS_DATA>-DATA = 'Celda 2'.

  APPEND INITIAL LINE TO TL_DATA ASSIGNING <FS_DATA>.
  <FS_DATA>-INDEXLIBRO = 1.
  <FS_DATA>-COLUMNA = 'C'.
  <FS_DATA>-CABECERA = ABAP_TRUE.
  <FS_DATA>-DATA = 'Celda 3'.

  APPEND INITIAL LINE TO TL_DATA ASSIGNING <FS_DATA>.
  <FS_DATA>-INDEXLIBRO = 1.
  <FS_DATA>-COLUMNA = 'D'.
  <FS_DATA>-CABECERA = ABAP_TRUE.
  <FS_DATA>-DATA = 'Celda 4'.
  <FS_DATA>-SALTODELINEA = ABAP_TRUE.

  CLEAR: VL_MONTOSTOTALES.


  VL_MONTOSTOTALES = VL_MONTOSTOTALES + 10.

  APPEND INITIAL LINE TO TL_DATA ASSIGNING <FS_DATA>.
  <FS_DATA>-INDEXLIBRO = 1.
  <FS_DATA>-COLUMNA = 'A'.
  <FS_DATA>-DATA = 'Valor'.

  APPEND INITIAL LINE TO TL_DATA ASSIGNING <FS_DATA>.
  <FS_DATA>-INDEXLIBRO = 1.
  <FS_DATA>-COLUMNA = 'B'.
  <FS_DATA>-DATA = 'Valor 2'.

  APPEND INITIAL LINE TO TL_DATA ASSIGNING <FS_DATA>.
  <FS_DATA>-INDEXLIBRO = 1.
  <FS_DATA>-COLUMNA = 'C'.
  <FS_DATA>-DATA = 'Valor 3'.

  APPEND INITIAL LINE TO TL_DATA ASSIGNING <FS_DATA>.
  <FS_DATA>-INDEXLIBRO = 1.
  <FS_DATA>-COLUMNA = 'D'.
  <FS_DATA>-DATA = 'Valor 4'.
  <FS_DATA>-SALTODELINEA = ABAP_TRUE.

  APPEND INITIAL LINE TO TL_MERGECELLS ASSIGNING FIELD-SYMBOL(<FS_MERGECELLS>).
  <FS_MERGECELLS>-INDEXLIBRO = 1.
  <FS_MERGECELLS>-INDEXMERGE = 3.
  <FS_MERGECELLS>-INICIO = 'A'.
  <FS_MERGECELLS>-FIN = 'C'.
  <FS_MERGECELLS>-VALORCELDA = 'Totales'.

  APPEND INITIAL LINE TO TL_TOTALES ASSIGNING FIELD-SYMBOL(<FS_TOTALES>).
  <FS_TOTALES>-INDEXLIBRO = 1.
  <FS_TOTALES>-COLUMNA = 'D'.
  <FS_TOTALES>-FILA = 3.
  WRITE VL_MONTOSTOTALES TO <FS_TOTALES>-VALORCELDA CURRENCY 'CLP'.

********************************* Libro 2 ******************************
  APPEND INITIAL LINE TO TL_LIBROS ASSIGNING <FS_LIBROS>.
  <FS_LIBROS>-INDEXLIBRO = 2.
  <FS_LIBROS>-LIBRO = 'Libro 2'.

  APPEND INITIAL LINE TO TL_DATA ASSIGNING <FS_DATA>.
  <FS_DATA>-INDEXLIBRO = 2.
  <FS_DATA>-COLUMNA = 'A'.
  <FS_DATA>-CABECERA = ABAP_TRUE.
  <FS_DATA>-DATA = 'Celda 1'.

  APPEND INITIAL LINE TO TL_DATA ASSIGNING <FS_DATA>.
  <FS_DATA>-INDEXLIBRO = 2.
  <FS_DATA>-COLUMNA = 'B'.
  <FS_DATA>-CABECERA = ABAP_TRUE.
  <FS_DATA>-DATA = 'Celda 2'.

  APPEND INITIAL LINE TO TL_DATA ASSIGNING <FS_DATA>.
  <FS_DATA>-INDEXLIBRO = 2.
  <FS_DATA>-COLUMNA = 'C'.
  <FS_DATA>-CABECERA = ABAP_TRUE.
  <FS_DATA>-DATA = 'Celda 3'.

  APPEND INITIAL LINE TO TL_DATA ASSIGNING <FS_DATA>.
  <FS_DATA>-INDEXLIBRO = 2.
  <FS_DATA>-COLUMNA = 'D'.
  <FS_DATA>-CABECERA = ABAP_TRUE.
  <FS_DATA>-DATA = 'Celda 4'.
  <FS_DATA>-SALTODELINEA = ABAP_TRUE.

  CLEAR: VL_MONTOSTOTALES.


  VL_MONTOSTOTALES = VL_MONTOSTOTALES + 10.

  APPEND INITIAL LINE TO TL_DATA ASSIGNING <FS_DATA>.
  <FS_DATA>-INDEXLIBRO = 2.
  <FS_DATA>-COLUMNA = 'A'.
  <FS_DATA>-DATA = 'Valor'.

  APPEND INITIAL LINE TO TL_DATA ASSIGNING <FS_DATA>.
  <FS_DATA>-INDEXLIBRO = 2.
  <FS_DATA>-COLUMNA = 'B'.
  <FS_DATA>-DATA = 'Valor 2'.

  APPEND INITIAL LINE TO TL_DATA ASSIGNING <FS_DATA>.
  <FS_DATA>-INDEXLIBRO = 2.
  <FS_DATA>-COLUMNA = 'C'.
  <FS_DATA>-DATA = 'Valor 3'.

  APPEND INITIAL LINE TO TL_DATA ASSIGNING <FS_DATA>.
  <FS_DATA>-INDEXLIBRO = 2.
  <FS_DATA>-COLUMNA = 'D'.
  <FS_DATA>-DATA = 'Valor 4'.
  <FS_DATA>-SALTODELINEA = ABAP_TRUE.

*  APPEND INITIAL LINE TO TL_MERGECELLS ASSIGNING <FS_MERGECELLS>.
*  <FS_MERGECELLS>-INDEXLIBRO = 2.
*  <FS_MERGECELLS>-INDEXMERGE = 3.
*  <FS_MERGECELLS>-INICIO = 'A'.
*  <FS_MERGECELLS>-FIN = 'C'.
*  <FS_MERGECELLS>-VALORCELDA = 'Totales'.
*
*  APPEND INITIAL LINE TO TL_TOTALES ASSIGNING <FS_TOTALES>.
*  <FS_TOTALES>-INDEXLIBRO = 2.
*  <FS_TOTALES>-COLUMNA = 'D'.
*  <FS_TOTALES>-FILA = 3.
*  WRITE VL_MONTOSTOTALES TO <FS_TOTALES>-VALORCELDA CURRENCY 'CLP'.

  CALL FUNCTION 'ZSD_DESCARGA_XLSX'
    EXPORTING
      I_LIBROS       = TL_LIBROS
      I_DATA         = TL_DATA
      I_MERGECELLS   = TL_MERGECELLS
      I_TOTALES      = TL_TOTALES.